'use strict';

var gulp = require('gulp');

gulp.paths = {
  src: 'www',
  dist: 'dist',
  tmp: '.tmp',
  e2e: 'e2e',
  sass: ['./scss/**/*.scss', 'www/**/*.scss'],
  js: ['!**/app-config.js', 'gulpfile.js', 'gulp/**/*', 'www/**/*.js',
    'e2e/**/*.js'
  ],
  html: ['www/*.html', 'www/**/*.html'],
  mockData: ['mock-data/cms/**']
};

/**
 * separating gulp tasks concerns inside the gulp dir
 * NOTE: tasks in this directory have been adapted from
 * tasks generated by github.com/kosz/generator-modular
 */
require('require-dir')('./gulp');

